BulkyWeb/Areas/Customer/Controllers/CartController.cs
using AspNetCore;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using System.Security.Claims;
using Microsoft.AspNetCore;

namespace BulkyWeb.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {


        private readonly IUnitOfWork _unitOfWork;
     /*   private readonly IEmailSender _emailSender;*/
        // tụ động điền dữ liệu khi có yêu cầu http
        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }

   /*     public CartController(IUnitOfWork unitOfWork,IEmailSender emailSender)
        {


            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
        }*/
        public CartController(IUnitOfWork unitOfWork)
        {


            _unitOfWork = unitOfWork;
            /*  _emailSender = emailSender;*/
        }
        public IActionResult Index()
        {
            // lay du lieu cua nguoi dang dang nhap
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ShoppingCartVM = new()
            {
                ShoppingCarts = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId, includeProperties: "Product"),
                OrderHeader = new OrderHeader()
            };
            foreach (var cart in ShoppingCartVM.ShoppingCarts)
            {
                cart.Price = GetPriceBaseOnQuantity(cart);
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
            }
            return View(ShoppingCartVM);
        }
      

        public IActionResult Summary()
        {

            // lay du lieu cua nguoi dang dang nhap
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            ShoppingCartVM = new()
            {
                ShoppingCarts = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId, includeProperties: "Product"),
                OrderHeader = new OrderHeader()
            };
          
            // lấy id người dùng trong 

            ShoppingCartVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId);
            ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.Name;
            ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
            ShoppingCartVM.OrderHeader.StreetAddress = ShoppingCartVM.OrderHeader.ApplicationUser.StreetAddress;
            ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.ApplicationUser.City;
            ShoppingCartVM.OrderHeader.State = ShoppingCartVM.OrderHeader.ApplicationUser.Status;
            ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.ApplicationUser.PostalCode;


            foreach (var cart in ShoppingCartVM.ShoppingCarts)
            {
                cart.Price = GetPriceBaseOnQuantity(cart);
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
            }

            return View(ShoppingCartVM);

        }

        [HttpPost]
        [ActionName("Summary")]
		public IActionResult SummaryPOST()
		{

			// lay du lieu cua nguoi dang dang nhap
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			ShoppingCartVM.ShoppingCarts = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId, includeProperties: "Product");
		
            ShoppingCartVM.OrderHeader.OrderDate =System.DateTime.Now;
            ShoppingCartVM.OrderHeader.ApplicationUserId = userId;

            /*ShoppingCartVM.OrderHeader.ApplicationUser =_unitOfWork.ApplicationUser.Get(u=>u.Id==userId);*/

            ApplicationUser applicationUser =_unitOfWork.ApplicationUser.Get(u=>u.Id==userId);



			foreach (var cart in ShoppingCartVM.ShoppingCarts)
			{
				cart.Price = GetPriceBaseOnQuantity(cart);
				ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
			}
            if (applicationUser.CompanyId.GetValueOrDefault() == 0)
            {

                // it is regular custome account 
                ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
                ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusPending;
            }
            else
            {
                // it is a company use
                ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusDelayedPayment;
                ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusApproved;
            }
            _unitOfWork.OrderHeader.Add(ShoppingCartVM.OrderHeader);
            _unitOfWork.Save();
            foreach(var cart in ShoppingCartVM.ShoppingCarts)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    ProductId = cart.ProductId,
                    OrderHeaderId = ShoppingCartVM.OrderHeader.Id,
                    Price = cart.Price,
                    Count = cart.Count
                };
                _unitOfWork.OrderDetail.Add(orderDetail);
                _unitOfWork.Save();
            }
            if (applicationUser.CompanyId.GetValueOrDefault() == 0)
            {

                // it is a regular customer account and we need to capture pay,emt
                //stripe logic   
                var domain = "https://localhost:7179/";

				var options = new SessionCreateOptions
                {
                    SuccessUrl = domain + $"customer/cart/OrderConfirmation?id={ShoppingCartVM.OrderHeader.Id}",
                    CancelUrl = domain +"customer/cart/index",
					/*  LineItems = new List<SessionLineItemOptions>()
					{
					  new SessionLineItemOptions
					  {
						Price = "price_H5ggYwtDq4fbrJ",
						Quantity = 2,
					  },
					},
					  Mode = "payment", */
					LineItems = new List<SessionLineItemOptions>(),
					Mode = "payment",
				};
                foreach(var item in ShoppingCartVM.ShoppingCarts)
                {
                    var sessionLineItem = new SessionLineItemOptions
                    {
                        PriceData = new SessionLineItemPriceDataOptions
                        {
                            UnitAmount = (long)(item.Price * 1000), //$20.50 => 2050
                            Currency = "usd",
                            ProductData = new SessionLineItemPriceDataProductDataOptions
                            {
                                Name = item.Product.Title
                            }
                        },
                        Quantity = item.Count
                    };
                    options.LineItems.Add(sessionLineItem);
                }
                var service = new SessionService();
             Session session =    service.Create(options);
                _unitOfWork.OrderHeader.UpdateStripePaymentID(ShoppingCartVM.OrderHeader.Id,session.Id, session.PaymentIntentId);
                _unitOfWork.Save();
                Response.Headers.Add("Location", session.Url);
                return new StatusCodeResult(303);

            }

            return RedirectToAction(nameof(OrderConfirmation), new {id= ShoppingCartVM.OrderHeader.Id});

		}


        public IActionResult OrderConfirmation( int id)
        {

            OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == id, includeProperties: "ApplicationUser");
            if(orderHeader.PaymentStatus!= SD.PaymentStatusDelayedPayment)
            {

                // this is an order by customer
                var service = new SessionService();
                Session session = service.Get(orderHeader.SessionId);
                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _unitOfWork.OrderHeader.UpdateStripePaymentID(id,session.Id,session.PaymentIntentId);
                    _unitOfWork.OrderHeader.UpdateStatus(id, SD.StatusApproved, SD.PaymentStatusApproved);
                    _unitOfWork.Save();
                    
                }
             
            
            }
          //  _emailSender.SendEmailAsync(orderHeader.ApplicationUser.Email, "New order - Bulky book", $"<p> New Order Created -{orderHeader.Id}</p>");

            List<ShoppingCart> shoppingCarts = _unitOfWork.ShoppingCart.GetAll(u=>u.ApplicationUserId == orderHeader.ApplicationUserId).ToList();
            _unitOfWork.ShoppingCart.RemoveRange(shoppingCarts);
            _unitOfWork.Save();
            return View(id);
        }
		public IActionResult Plus(int cartId)
        {
           

            var cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == cartId);
            cartFromDb.Count += 1;
            _unitOfWork.ShoppingCart.Update(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Minus(int cartId)
        {
            var cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == cartId);
            if (cartFromDb.Count <= 1)
            {
                _unitOfWork.ShoppingCart.Remove(cartFromDb);
            }
            else
            {
                cartFromDb.Count -= 1;
                _unitOfWork.ShoppingCart.Update(cartFromDb);
            }


            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int cartId)
        {
            var cartFromDb = _unitOfWork.ShoppingCart.Get(u => u.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cartFromDb);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }

BulkyWeb/Areas/Customer/Views/Cart/Index.cshtml
@model ShoppingCartVM
<form method="post">
   
    <br />
    <div class="card shadow border-0">
        <div class="card-header bg-secondary bg-gradient text-light ml-0 py-4">
            <div class="row px-4">
                <div class="col-6">
                    <h5 class="pt-2 text-white">
                        Shopping Cart
                    </h5>
                </div>

            </div>
        </div>
        <div class="card-body my-4">
            <div class="row">
            </div>
            <div class="row mb-3 pb-3">
                <div class="col-md-2 offset-md-1">
                    <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="btn btn-outline-primary text-uppercase mb-5 btn-sm"><small>Continue Shopping</small></a>
                </div>
                <div class="col-md-10 offset-md-1">

                    @foreach(var item in Model.ShoppingCarts)
                    {
                        
                    <div class="row border-bottom pb-3">
                        <div class="d-none d-lg-block col-lg-1 text-center py-2">
                            <img src="@item.Product.ImageUrl" class="rounded" width="100%" />
                        </div>
                        <div class="col-12 col-lg-6 pt-md-3">
                            <h5 class="text-uppercase text-secondary"><strong>@item.Product.Price</strong></h5>
                            <p><small>@Html.Raw(item.Product.Description)</small></p>
                        </div>
                        <div class="col-12  col-lg-5 text-center row">
                            <div class="col-3 text-md-right pt-2 pt-md-4">
                                <h6 class="fw-semibold">
                                   @item.Price.ToString("c")
                                    <span class="text-muted">&nbsp;x&nbsp;</span>@item.Count
                                </h6>
                            </div>
                            <div class="col-6 col-sm-4 col-lg-6 pt-2">
                                <div class="w-75 btn-group" role="group">
                                    <a asp-action="plus" asp-route-cartId="@item.Id" class="btn btn-outline-primary bg-gradient py-2">
                                        <i class="bi bi-plus-square"></i>
                                    </a> &nbsp;
                                        <a asp-action="minus" asp-route-cartId="@item.Id" class="btn btn-outline-primary bg-gradient py-2">
                                        <i class="bi bi-dash-square"></i>
                                    </a>
                                </div>

                            </div>
                            <div class="col-3 col-sm-4 col-lg-2 offset-lg-1 text-right pt-2">
                                    <a asp-action="remove" asp-route-cartId="@item.Id" class="btn btn-danger bg-gradient py-2 ">
                                    <i class="bi bi-trash-fill"></i>
                                </a>
                            </div>
                        </div>

                    </div>
                    }


                </div>
            </div>
            <div class="card-footer bg-white border-0">
                <div class="row">
                    <div class="col-md-4 offset-md-4">
                        <ul class="list-group mb-4">
                            <li class="d-flex justify-content-between align-items-center">
                                <h5 class="text-dark fw-semibold text-uppercase"> Total (USD)</h5>
                                <h4 class="text-dark fw-bolder">@Model.OrderHeader.OrderTotal.ToString("c")</h4>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2 offset-md-5">
                        <a asp-action="Summary" class="btn btn-primary border-0 bg-gradient w-100 py-2">Summary</a>
                    </div>
                </div>
            </div>
        </div>
</form>

BulkyWeb/Areas/Customer/Views/Cart/OrderConfirmation.cshtml
@model int
<div class="container row pt-4">
    <div class="col-12 text-center">
        <h1 class="text-primary text-center">Order Placed Successfully</h1>
        Your Order Number is :@Model<br /><br />
        <img src="~/images/product/0421b086-a810-40e0-8e5c-3f708d23d0b4.webp" />

    </div>
    <div class="col-12 text-center" style="color:maroon">
        <br />
        Your order has been placed successfully! <br />
    </div>
</div>

BulkyWeb/Areas/Customer/Views/Cart/Summary.cshtml
@model ShoppingCartVM
<form method="post">
	<br />
	<div class="container">
		<div class="card shadow border-0">
			
			<div class="card-header bg-secondary bg-gradient text-light ml-0 py-4">
				<div class="row px-4">
					<div class="col-6">
						<h5 class="pt-2 text-white">
							Order Summary
						</h5>
					</div>
				<div class="col-6 text-end">
					<a  asp-action="Index" class="btn btn-outline-danger btn-sm">Back to Cart</a>
				</div>
				</div>
			</div>
			<div class="card-body">
				<div class="container rounded p-2">
					<div class="row">
						<div class="col-12 col-lg-6 pb-4">
							<div class="row">
								<h4 class="d-flex justify-content-between align-items-center mb-3">
									<span class="text-info">Shipping Details:</span>
								</h4>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Name</label>
								</div>
								<div class="col-9">
									  <input asp-for="OrderHeader.Name" class="form-control" />
									  <span asp-validation-for="OrderHeader.Name" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Phone</label>
								</div>
								<div class="col-9">
									<input asp-for="OrderHeader.PhoneNumber" class="form-control" />
									<span asp-validation-for="OrderHeader.PhoneNumber" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Street Address</label>
								</div>
								<div class="col-9">
									<input asp-for="OrderHeader.StreetAddress" class="form-control" />
									<span asp-validation-for="OrderHeader.StreetAddress" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>City</label>
								</div>
								<div class="col-9">
									<input asp-for="OrderHeader.City" class="form-control" />
									<span asp-validation-for="OrderHeader.City" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>State</label>
								</div>
								<div class="col-9">
									<input asp-for="OrderHeader.State" class="form-control" />
									<span asp-validation-for="OrderHeader.State" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Postal Code</label>
								</div>
								<div class="col-9">
									<input asp-for="OrderHeader.PostalCode" class="form-control" />
									<span asp-validation-for="OrderHeader.PostalCode" class="text-danger"></span>
								</div>
							</div>
						</div>
						<div class="col-12 col-lg-5 offset-lg-1">
							<h4 class="d-flex justify-content-between align-items-center mb-3">
								<span class="text-info">Order Summary:</span>
							</h4>
							<ul class="list-group mb-3">
								@foreach(var details in Model.ShoppingCarts)
								{
									<li class="list-group-item d-flex justify-content-between">
										<div>
											<h6 class="my-0">@details.Product.Title</h6>
											<small class="text-muted">Quantity: @details.Count</small>
										</div>
										<span class="text-muted">@((details.Price*details.Count).ToString("c"))</span>
									</li>
								}
								


								<li class="list-group-item d-flex justify-content-between bg-light">
									<small class="text-info">Total (USD)</small>
									<strong class="text-info">@Model.OrderHeader.OrderTotal</strong>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="card-footer">
				<div class="row">
					<div class="col-12 col-md-8 pt-2">
						<p style="color:maroon; font-size:14px;">
							Estimate Arrival Date:
							@DateTime.Now.AddDays(7).ToShortDateString - @DateTime.Now.AddDays(14).ToShortDateString()
							
						</p>
					</div>
					<div class="col-12 col-md-4">
						<button type="submit" value="Place Order" class="btn btn-primary form-control">Place Order</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>