BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.DataAccess;
using Bulky.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bulky.Models.ViewModels;
using System.Drawing;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
     
        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
          
        }
        public IActionResult Index()
        {
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();
            /* List<Category> categories = _unitOfWork.Category.GetAll().ToList();*/
            return View(objCompanyList);
        }
        public IActionResult Upsert(int? id)
        {



            if (id == null || id == 0)
            {
                // create 
                return View(new Company());
            }
            else
            {
                Company company = _unitOfWork.Company.Get(u => u.Id == id);
                return View(company);
            }


        }

        /* ViewData["CategoryList"] = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
         {
             Text = u.Name,
             Value = u.Id.ToString()
         });

         CompanyVM CompanyVm = new CompanyVM()
         {
             Company = new Company()
         };
         return View(CompanyVm);*/
        /*}*/


        [HttpPost]
        public IActionResult Upsert(Company companyObj)
        {
            if (ModelState.IsValid)
            {
                if (companyObj.Id == 0)
                {
                    _unitOfWork.Company.Add(companyObj);
                }
                else
                {
                    _unitOfWork.Company.Update(companyObj);
                }
                _unitOfWork.Save();
                TempData["success"] = "Them thanh cong";
                return RedirectToAction("Index");

            }
            else
            {
                return View(companyObj);
            }
           

           
        }
    



      
/*
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Company? CompanyFromDb = _unitOfWork.Producdt.Get(u => u.Id == id);
            if (CompanyFromDb == null)
            {
                return NotFound();
            }
            return View(CompanyFromDb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Company? Company = _unitOfWork.Producdt.Get(u => u.Id == id);
            if (Company == null)
            {
                return NotFound();
            }
            _unitOfWork.Producdt.Remove(Company);
            _unitOfWork.Save();
            TempData["success"] = "Delete thanh cong";
            return RedirectToAction("Index");
        }*/

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll() {
            List<Company> objCompanyList = _unitOfWork.Company.GetAll().ToList();
            return Json(new {data = objCompanyList});
        }

        [HttpDelete]
        public IActionResult Delete(int? id) {
        var CompanyToBeDelete = _unitOfWork.Company.Get(u=>u.Id == id);
            if(CompanyToBeDelete == null) {

                return Json(new { success = false, message = "Error while deleting" });
            }
          
            _unitOfWork.Company.Remove(CompanyToBeDelete);
            _unitOfWork.Save();
          
            return Json(new { success = false, message = "Delete  success" });
        }
        #endregion
    }

}

BulkyWeb/Areas/Admin/Controllers/ProductController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.DataAccess;
using Bulky.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bulky.Models.ViewModels;
using System.Drawing;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Product> objProductList = _unitOfWork.Producdt.GetAll(includeProperties:"Category").ToList();
           /* List<Category> categories = _unitOfWork.Category.GetAll().ToList();*/
            return View(objProductList);
        }
        public IActionResult Upsert(int? id)
        {


            ProductVM productVm = new ProductVM()
            {
                CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Product = new Product()
            };
            if(id == null || id == 0)
            {
                // create 
                return View(productVm);
            }
            else
            {
                productVm.Product = _unitOfWork.Producdt.Get(u => u.Id == id);
                return View(productVm);
            }
           

        } 

           /* ViewData["CategoryList"] = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            ProductVM productVm = new ProductVM()
            {
                Product = new Product()
            };
            return View(productVm);*/
        /*}*/

     
        [HttpPost]
        public IActionResult Upsert(ProductVM productVM, IFormFile ? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if(file!= null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    String productPath = Path.Combine(wwwRootPath, @"images\product");

                    // thuc hien xoa hinh anh hien tai
                    if (!string.IsNullOrEmpty(productVM.Product.ImageUrl))
                    {
                        // delete the old image
                        var oldImagePath = Path.Combine(wwwRootPath,productVM.Product.ImageUrl.TrimStart('\\'));
                        if(System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(productPath, fileName),FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    productVM.Product.ImageUrl = @"\images\product\" + fileName;
                }
                if (productVM.Product.Id == 0)
                {
                    _unitOfWork.Producdt.Add(productVM.Product);
                }
                else
                {
                    _unitOfWork.Producdt.Update(productVM.Product);
                }
               
                _unitOfWork.Save();
                TempData["success"] = "Them thanh cong";
                return RedirectToAction("Index");
            }
            else
            {

                productVM.CategoryList = _unitOfWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
               
             
                return View(productVM);
              
            }
          
          
        }



      
/*
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Product? productFromDb = _unitOfWork.Producdt.Get(u => u.Id == id);
            if (productFromDb == null)
            {
                return NotFound();
            }
            return View(productFromDb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Product? product = _unitOfWork.Producdt.Get(u => u.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            _unitOfWork.Producdt.Remove(product);
            _unitOfWork.Save();
            TempData["success"] = "Delete thanh cong";
            return RedirectToAction("Index");
        }*/

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll() {
            List<Product> objProductList = _unitOfWork.Producdt.GetAll(includeProperties: "Category").ToList();
            return Json(new {data = objProductList});
        }

        [HttpDelete]
        public IActionResult Delete(int? id) {
        var productToBeDelete = _unitOfWork.Producdt.Get(u=>u.Id == id);
            if(productToBeDelete == null) {

                return Json(new { success = false, message = "Error while deleting" });
            }
            // delete the old image
            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, productToBeDelete.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _unitOfWork.Producdt.Remove(productToBeDelete);
            _unitOfWork.Save();
          
            return Json(new { success = false, message = "Delete  success" });
        }
        #endregion
    }
}

BulkyWeb/Areas/Admin/Views/Company/Delete.cshtml
@model Product


<div cite="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> Delete Product</h2>

            </div>
        </div>
    </div>

    <div class="card-body p-4">

        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                <div cite="row pb-2">
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Title" disabled class="form-control border-0 shadow" />
                        <label asp-for="Title" class="ms-2"></label>
                    </div>

                    <div class="form-floating py-2 col-12">
                        <input asp-for="Description" disabled class="form-control border-0 shadow" />
                        <label asp-for="Description" class="ms-2"></label>
                    </div>

                    <div class="form-floating py-2 col-12">
                        <input asp-for="ISBN" disabled class="form-control border-0 shadow" />
                        <label asp-for="ISBN" class="ms-2"></label>
                    </div>

                    <div class="form-floating py-2 col-12">
                        <input asp-for="Author" disabled class="form-control border-0 shadow" />
                        <label asp-for="Author" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="ListPrice" disabled class="form-control border-0 shadow" />
                        <label asp-for="ListPrice" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Price" disabled class="form-control border-0 shadow" />
                        <label asp-for="Price" class="ms-2"></label>
                    </div>
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Price50" disabled class="form-control border-0 shadow" />
                        <label asp-for="Price50" class="ms-2"></label>
                    </div>

                    <div class="form-floating py-2 col-12">
                        <input asp-for="Price100" disabled class="form-control border-0 shadow" />
                        <label asp-for="Price100" class="ms-2"></label>
                    </div>



                </div>
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Delete </button> 

                    </div>

                    <div class="col-6 col-md-3">
                        <a asp-controller="Product" asp-action="Index" class="btn  btn-outline-secondary form-control">
                            Back to List
                        </a>
                    </div>
                </div>


            </div>
        </form>
    </div>

</div>

BulkyWeb/Areas/Admin/Views/Company/Index.cshtml
<div cite="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Company List</h2>

            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <div class="row  pb-3">
            <div class="col-6">
              
            </div>

            <div class="col-6 text-end">
                <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus"></i>  Create New Company
                </a>
            </div>
        </div>
        <table id="tblData" class="table table-bordered table-striped">
            <thead>



                <tr>
                   <th>Name</th>
                   <th>Address</th>
                   <th>City</th>
                   <th>State</th>
                   <th>Phone Number</th>
                    <th></th>
                </tr>

            </thead>
          @*  <tbody>



                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Title</td>
                        <td>@obj.ISBN</td>
                        <td>@obj.ListPrice</td>
                        <td>@obj.Author</td>
                        <td>
                            @obj.Category.Name
                        </td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Product" asp-action="Upsert" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a> 

                                <a asp-controller="Product" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-x"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }


            </tbody>*@
        </table>

    </div>

</div>


@*   <div class="container">
      
</div>*@

@section Scripts{
    <script src="/js/company.js"></script>
}                           

BulkyWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div cite="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">@(Model.Id != 0 ? "Update" : "Create") Company</h2>

            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />

            <div class="row">
                <div class="col-12">
                    <div class="border p-3">

                        @*<div asp-validation-summary="ModelOnly"></div>*@
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Name" class="form-control border-0 shadow" />
                            <label asp-for="Name" class="ms-2"></label>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="PhoneNumber" class="form-control border-0 shadow" />
                            <label asp-for="PhoneNumber" class="ms-2"></label>
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="StreetAddress" class="form-control border-0 shadow" />
                            <label asp-for="StreetAddress" class="ms-2"></label>
                            <span asp-validation-for="StreetAddress" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="City" class="form-control border-0 shadow" />
                            <label asp-for="City" class="ms-2"></label>
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="State" class="form-control border-0 shadow" />
                            <label asp-for="State" class="ms-2"></label>
                            <span asp-validation-for="State" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="PostalCode" class="form-control border-0 shadow" />
                            <label asp-for="PostalCode" class="ms-2"></label>
                            <span asp-validation-for="PostalCode" class="text-danger"></span>
                        </div>








                        <div class="row">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                }

                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Company" asp-action="Index" class="btn btn-outline-primary border form-control">
                                    Back to List
                                </a>
                            </div>
                        </div>
                    </div>
                </div>



            </div>




        </form>
    </div>

</div>


@section Scripts{
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ]
        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}